### ISSUE TITLE
Pip install fails on Python2

### ISSUE THREAD

**Issue by spyoungtech** [spyoungtech/behave-webdriver#65]
Pip fails due to use of `encoding` argument in `setup.py`, which is not valid in Python2.

```
$ python2 -m pip install behave-webdriver
Collecting behave-webdriver
  Downloading https://files.pythonhosted.org/packages/f7/bc/61ac3c54a823f19e98c191fcd3b922bd7eb9281086bb8eb39ec14b123f2e/behave-webdriver-0.2.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/vk/1l_9vpz54bb6rhmg7twwxfyw0000gp/T/pip-install-w5AozC/behave-webdriver/setup.py", line 3, in <module>
        with open('README.rst', 'rt', encoding='utf8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function
```

**Comment by spyoungtech** [comment]
So, our CI build for Py2 didn't catch this, since we do not actually `pip install .` as part of the build process and just use `requirements.txt` instead.

Not sure if that's something we should change; is it better to use `pip install .` or `pip install -r requirements.txt` for CI build?

As far as I can tell it'd be functionally equivalent to switch it up. This would also (maybe?) help ensure that the package can be installed in different versions of Python.

**Comment by spyoungtech** [comment]
Also noticed travis only produced a py3 wheel. Should include a `setup.cfg` specifying universal wheels like so:

```
[bdist_wheel]
universal = 1
```

As far as I know, this is fine for us, since the project is compatible in both versions and we don't use any C extensions.

**Comment by spyoungtech** [comment]
Also added license metadata to `setup.cfg`

```
[metadata]
license_file = LICENSE
```

So wheel distributions include license file.

**Comment by spyoungtech** [comment]
Another 386 days from now and this wouldn't have been an issue! 

https://pythonclock.org/

Can't wait!

**Comment by spyoungtech** [comment]
Done. Py2 now installs with pip/setup.py just fine and has wheel on pypi.

Didn't adjust CI build install phase, but should be fine™️ !
