### ISSUE TITLE
can't run minimal-project

### ISSUE THREAD

**Issue by mikelietz** [spyoungtech/behave-webdriver#68]
I'm attempting to use this in Python 2.7 on a Mac. I installed behave and behave-webdriver via pip.

    examples $ cd minimal-project/
    minimal-project $ behave
    Exception ImportError: cannot import name BehaveDriver
    Traceback (most recent call last):
      File "/usr/local/bin/behave", line 11, in <module>
        sys.exit(main())
      File "/usr/local/lib/python2.7/site-packages/behave/__main__.py", line 183, in main
        return run_behave(config)
      File "/usr/local/lib/python2.7/site-packages/behave/__main__.py", line 127, in run_behave
        failed = runner.run()
      File "/usr/local/lib/python2.7/site-packages/behave/runner.py", line 804, in run
        return self.run_with_paths()
      File "/usr/local/lib/python2.7/site-packages/behave/runner.py", line 808, in run_with_paths
        self.load_hooks()
      File "/usr/local/lib/python2.7/site-packages/behave/runner.py", line 784, in load_hooks
        exec_file(hooks_path, self.hooks)
      File "/usr/local/lib/python2.7/site-packages/behave/runner_util.py", line 386, in exec_file
        exec(code, globals_, locals_)
      File "features/environment.py", line 1, in <module>
        from behave_webdriver import BehaveDriver
    ImportError: cannot import name BehaveDriver

**Comment by spyoungtech** [comment]
Thanks for reporting this issue @mikelietz 

It looks like there are two problems here.

(1) The minimal example will need to be updated for the current release, as `BehaveDriver` has been removed and replaced with regular selenium class names.

(2) The selenium-requests example, as written, only works on Python3 right now. Though, making this example Py2 compatible shouldn't be too much work.

I'll address these problems shortly.

**Comment by spyoungtech** [comment]
Hey @mikelietz 

I just updated the examples in the `master` branch. In the process, I also discovered another bug ( #69 ) along the way, which I just merged a patch for and released in v0.2.2

You should be all set with these latest changes. Let me know if that works for you.

**Comment by spyoungtech** [comment]
This is the other bug ( #69 ) I mentioned. The fix for this was released in v0.2.2 
So you shouldn't run into this if using the latest version.

If you installed behave-webdriver with `pip` you can upgrade it like so

```python
pip install --upgrade behave-webdriver
```
